// <auto-generated />
namespace ErdalBakkal.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class UserandRole4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserandRole4));
        
        string IMigrationMetadata.Id
        {
            get { return "202003091740077_UserandRole4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
